version: '3.7'
services:
  elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
  container_name: elasticsearch
  restart: always
  volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
  ports:
    - 9200:9200

kibana:
  container_name: kibana
  image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
  restart: always
  environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  ports:
    - 5601:5601
  depends_on:
    -  elasticsearch

volumes:
  elasticsearch-data-volume:
    driver: local